Gemfile
see https://github.com/igrigorik/...em-synchrony/issues/189
This pins the Gemfile to 1.0.3 which seems to work.
This gets the CI tests running again.
=> em-synchrony 1.0.4 seems to be broken

gemfiles/3.1.gemfile, gemfiles/3.2.gemfile
Allow any version of mysql > 2.8.1 instead of just 2.8.1.  2.8.2 was yanked and 2.8.1 does not seem to build on OS X 10.10
=> Relax restrictions on mysql for AR 3.1 and 3.2

lib/activerecord-import/import.rb
I have a client that is using AR-import on an STI table and is upgrading to rails 4. This code breaks on upgrade because `scope_attributes` returns both `:type` and `"type"`. Since de-duping is happening via an `include?` check against a symbol, the inserted value should be cast to a symbol as well.
=> Fix a typing issue to dedupe column_names on import

lib/activerecord-import.rb
By default const_defined? looks for constant in all ancestors of the module including Object. 
In my case I included another gem in my project with global namespace "Import". After that activerecord-import stopped to require own code because ActiveRecord.const_defined?(:Import) returns true.
=> Fix global constant lookup

lib/activerecord-import/import.rb
I did some profiling and found that a lot of time is spent quoting the timestamps for every single row, even though the result is the same each time. We can prevent this from happening by quoting them beforehand instead. This gave me about a 5% speed boost.
=> Prequote timestamps for a speed boost

lib/activerecord-import/import.rb, test/support/mysql/assertions.rb, test/support/mysql/import_examples.rb
There is currently no option to tell the MySQL importer to fail on duplicate entries. I added this support locally for rails 3 and decided to PR this feature back for the master fork. Now if you explicitly set `:on_duplicate_key_update => false` in the import options it won't allow for duplicate keys to update existing elements. This was important for an application where all the data being imported should be new rows and any duplicates indicates an error in the input data.
It would be nice if there was a way to create a new branch/release for rails 3 to get updates that the rails 4 master branch is receiving (so I can reference your master fork instead of the PR fork).
=> Allow for `:on_duplicate_key_update` to be turned off

lib/activerecord-import/adapters/postgresql_adapter.rb, test/support/postgresql/import_examples.rb
Commit ee7411acaf32db233edb611e3d0ed885a2b589f5 defined an `insert_many` method in `ActiveRecord::Import::PostgreSQLAdapter`. As this method uses `select_values`, the ActiveRecord query cache is not invalidated after the query is executed.
This pull request invalidates the cache by calling `ActiveRecord::Base.connection.query_cache.clear` immediately after `select_values` is called.
=> postgresql adapter clears cache on insert_many

test/support/mysql/import_examples.rb
Currently the MySQL test suite explicitly disables MySQL strict mode. The test suite passes in strict mode with changes to only one test though, and strict mode is now the default [as of Rails 4](http://guides.rubyonrails.org/4_0_release_notes.html), so it seems preferable to test in strict mode.
=> Support MySQL strict mode, and use for tests

lib/activerecord-import/import.rb, test/import_test.rb
This is needed to avoid that rails try to save a new object of this
model if later you use one of the imported objects (with the id set) in
an association with other new model that is being saved in database.
=> Set new_record to false after set model ids

README.markdown
This just adds a little formatting to separate the two associations in the hypothetical schema to make it a little easier to read.
=> Separate associations in example schema

lib/activerecord-import.rb
ActiveSupport.on_load is not just a way to add an additional block of code into a Ruby method.
It's a mechanism for adding load hooks which is needed to implement lazy loading in ActiveSupport.
And, in this particular after_established case, we don't actually need any special mechanism. Let's just simply call the logic inside the AMC.
This is to get changes in #177 implemented by @amatsuda  in.
=> Don't use AS.on_load for something else than on_load hook

lib/activerecord-import/adapters/abstract_adapter.rb, lib/activerecord-import/adapters/mysql_adapter.rb, lib/activerecord-import/adapters/postgresql_adapter.rb, lib/activerecord-import/import.rb, test/em_mysql2/import_test.rb, test/jdbcmysql/import_test.rb, test/jdbcpostgresql/import_test.rb, test/models/promotion.rb, test/mysql/import_test.rb, test/mysql2/import_test.rb, test/mysqlspatial/import_test.rb, test/mysqlspatial2/import_test.rb, test/postgresql/import_test.rb, test/schema/generic_schema.rb, test/support/assertions.rb, test/support/mysql/import_examples.rb, test/support/postgresql/import_examples.rb, test/support/shared_examples/on_duplicate_key_update.rb
Postgres 9.5 added UPSERT support. Resolves #187.
Provides the following syntax:
```
Country.import [country], validate: false, on_duplicate_key_update: { conflict_target: :country, columns: [:updated_at] }
```
`:conflict_target` takes either a single value or an array of column names that make up the unique constraint and `:columns` could be either an array or hash similar to the existing MySQL functionality.
=> Add :on_duplicate_key_update support for Postgres

lib/activerecord-import/import.rb, test/import_test.rb, test/models/book.rb, test/schema/generic_schema.rb
First, _ENV['AR_VERSION'].to_i > 4.1_ is only true when _AR_VERSION >= 5_ because _to_i_ rounds down strings, e.g. _"4.2".to_i => 4_. Therefore, in 4.2 the enum in book.rb is not currently defined.
And the main stuff is, for many adapters the default value of an integer column is still in string format (like in postgresql by using pg_get_expr, check at: http://www.postgresql.org/docs/8.0/static/functions-info.html#AEN13319) before type casting. So during the importing, an argument error happens like _ArgumentError: '0' is not a valid status_, given 0 is the default value for status column. This issue seems not only to happen in postgresql.
There's no new test cases for this PR, because some existing tests get failed when default value is added and enum is enabled in book.rb. Certainly, …
=> Fix rails (> 4.1) enum column with a default integer value

test/schema/generic_schema.rb, test/test_helper.rb
When running the tests for AR 4.2 the following deprecation warnings are displayed:
```
DEPRECATION WARNING: `#timestamps` was called without specifying an option for `null`.
In Rails 5, this behavior will change to `null: false`. You should manually specify `null: true`
to prevent the behavior of your existing migrations from changing. (called from block (2 levels)
in <top (required)> at /Users/jordan/projects/activerecord-import/test/schema/generic_schema.rb:10)
```
```
DEPRECATION WARNING: You did not specify a value for the configuration option `active_support.test_order`.
In Rails 5, the default value of this option will change from `:sorted` to `:random`.
To disable this warning and keep the current behavior, you can add the following
line to your `config/environments/test.rb`: …
```
=> Cleanup Rails 5 deprecation warnings in tests

test/travis/build.sh
This makes the output on TravisCI look like this in the success case:
In the failure case it will show the full output for which run failed.
=> Updating travisci build to be less verbose on successful runs.

lib/activerecord-import/import.rb, test/models/book.rb, test/models/question.rb, test/models/topic.rb
Based on @sferik's work in PR #230
=> Recursively import all has_one/has_many associations

lib/activerecord-import/import.rb, test/support/postgresql/import_examples.rb
Only use :on_duplicate_key_update option when importing top level models. Fixes #249.
=> Fix issue doing recursive import with :on_duplicate_key_update

lib/activerecord-import/import.rb, test/import_test.rb
When using `import!` an ActiveRecord::RecordInvalid error is raised if any of the validations fail. Resolves #162.
=> Add import! method

Gemfile, gemfiles/4.0.gemfile, gemfiles/4.1.gemfile, gemfiles/4.2.gemfile, lib/activerecord-import/import.rb, lib/activerecord-import/synchronize.rb, test/import_test.rb, test/support/active_support/test_case_extensions.rb, test/test_helper.rb
Tests were only running for latest AR 4.2 because the version specifier wasn't to the patch level.
Once tests were running an issue with :synchronize showed up for AR 4.0 and 4.1. This PR incorporates the fix in #176.
Also found that tests for serialization weren't running and JSON serialization was failing on AR < 4.2. Fixes #211.
=> Fix issues running tests for AR 4.0 and 4.1

lib/activerecord-import/import.rb, test/import_test.rb
This resolves #207. Batch size defaults to the total number of records to import. I considered using 1000 records per insert as a default as that seems to be fairly standard, but I decided it might be better to have it as an explicit option for now. I'm open to other suggestions :smile: 
See [ActiveRecord::Batches](http://api.rubyonrails.org/classes/ActiveRecord/Batches.html).
=> Add :batch_size option to import

benchmarks/lib/output_to_html.rb
The shovel operator has higher precedence than the equality operator.
=> Fix benchmark html report

.travis.yml, activerecord-import.gemspec, gemfiles/3.1.gemfile, lib/activerecord-import/import.rb, lib/activerecord-import/synchronize.rb
Rails 3.1 is no longer being maintained, [even for severe security issues](http://guides.rubyonrails.org/maintenance_policy.html). The last 3.1.x release, [was 3 years ago](https://rubygems.org/gems/activerecord/versions).
This will also make the Travis CI build run significantly faster, since we can run 5 builds in parallel and this is the 6th build, so it has to wait for all the other Active Record versions to finish before it can start.
=> Drop support for Rails 3.1

Gemfile, test/database.yml.sample, test/travis/database.yml
This will resolve the failing seamless_database_pool tests for AR 5.0. Note that AR 3.1 is not supported by the seamless_database_pool gem as of version 1.0.18 (which adds AR 5.0RC1 support).
=> Upgrade seamless_database_pool to support AR 5.0

lib/activerecord-import/adapters/sqlite3_adapter.rb, lib/activerecord-import/import.rb, test/sqlite3/import_test.rb, test/support/postgresql/import_examples.rb, test/support/shared_examples/recursive_import.rb
As requested in #247.
Sqlite doesn't support concurrent write operations, so it can be assumed all ids for a batch insert will be sequential.
This also extracts the recursive import tests out into a shared example so that they can be applied to other adapters. If all adapters eventually get this functionality, the specs could be moved into the main spec file.
=> Add recursive import support for sqlite3

lib/activerecord-import.rb
=> Remove deprecated use of `alias_method_chain` in Rails 5

lib/activerecord-import/adapters/abstract_adapter.rb, lib/activerecord-import/import.rb, test/support/postgresql/import_examples.rb, test/support/shared_examples/on_duplicate_key_update.rb
Recursive import depends on the primary keys of the parent model being returned, but :on_duplicate_key_ignore doesn't return ids for duplicate records. It is possible then, that a model will be assigned the wrong id and its children would be associated with the wrong parent.
Fixes #267.
=> Prevent :on_duplicate_key_ignore being used when :recursive enabled

lib/activerecord-import/adapters/postgresql_adapter.rb, test/support/postgresql/import_examples.rb
Motivation for this PR: enable import without `RETURNING` clause (right now for every INSERT statement `RETURNING` clause is applied). This will allow to use Postgres rules for insertion, for example the rule to simply ignore all duplications inside INSERT statement.
Right now if we have smth like this in DB (Postgres younger than 9.5)
~~~
CREATE OR REPLACE RULE events_duplicate_ignore AS ON insert TO events
WHERE EXISTS(
SELECT 1
FROM events
WHERE (mask)=(NEW.mask)
)
DO INSTEAD NOTHING;
~~~
and try to insert duplicate we'll have an error `ActiveRecord::StatementInvalid: PG::FeatureNotSupported: ERROR: cannot perform INSERT RETURNING on relation "events" HINT: You need an unconditional ON INSERT DO INSTEAD rule with a RETURNING clause.`
=> Added no_returning option for Postgres to insert without RETURNING clause

lib/activerecord-import/import.rb, test/import_test.rb
Currently, when validating models on import, the models are converted to arrays of values and then are reinitialized as models to call `valid?` It seems unnecessary to do this extra reinitialization step. Inspired by #118.
Running the MySQL benchmarks on my laptop shows a 2x performance increase (over previous implementation) for importing models with validations.
=> Improve performance of importing models with validations

lib/activerecord-import/import.rb, test/import_test.rb
=> Prevent modification of input array

gemfiles/4.2.gemfile, lib/activerecord-import/import.rb
Fix NoMethodError: undefined method `raise_record_invalid'.
Method name changed 'raise_record_invalid' to 'raise_validation_error' in Rails 5.0.
https://github.com/rails/rails/commit/830b7041f213669c3877edf459ef83a31c84cc4d
=> Fix undefined method `raise_record_invalid' on Rails 5.0

lib/activerecord-import/adapters/postgresql_adapter.rb, test/support/postgresql/import_examples.rb
If no conflict target is specified, and a table does not have a primary key, an `ArgumentError` is raised with the message:
```
Expected :conflict_target or :constraint_name to be specified
```
Currently, a `ActiveRecord::StatementInvalid` error is raised because the SQL is generated without any conflict target value:
```
ON CONFLICT () DO UPDATE SET
```
=> Raise ArgumentError if no conflict_target available

test/import_test.rb, test/models/widget.rb, test/schema/generic_schema.rb
While trying to track down bug between activerecord-import and another gem wrote more test coverage to rule out that issue was caused by activerecord-import. This pull requests only adds more test coverage.
=> Improve test coverage for serailzed attributes

lib/activerecord-import/import.rb, test/import_test.rb
Prevents a `NoMethodError: undefined method 'each' for nil:NilClass` if :recursive option was erroneously set when importing with an array of columns and an array of values.
Instead the :recursive option is ignored and the import is completed.
=> Only attempt recursive import when passed array of models

lib/activerecord-import/import.rb, test/schema/generic_schema.rb
While using recursive option same primary key is used for all activerecords. Which fails when a activerecord has different primary key name or doesn't have one.
=> Same primary key on recursive issue resolved

lib/activerecord-import/import.rb, test/models/dictionary.rb, test/schema/generic_schema.rb, test/support/shared_examples/recursive_import.rb
The commits fixes the import a subclass of STI with polymorphic associations. It was getting the model class name to the polymorphic record instead of its parent class name.
=> Updating support for import from a STI subclass with polymorphic associations 

lib/activerecord-import/adapters/sqlite3_adapter.rb, lib/activerecord-import/import.rb, test/import_test.rb
In `support_setting_primary_key_of_imported_objects? == true` adapters like Postgres, `set_ids_and_mark_clean` iterates returned ids and set them to models (include both valid and invalid). It seems that this method should ignore invalid models.
=> fix setting returned ids to wrong models

test/import_test.rb
Confirms that activerecord-import works with STI models. Resolves #265.
=> Add test for importing STI models

.travis.yml, lib/activerecord-import/import.rb, test/import_test.rb, test/models/vendor.rb, test/postgis/import_test.rb, test/schema/generic_schema.rb, test/schema/postgresql_schema.rb, test/support/postgresql/import_examples.rb
Add support for setting attributes on serialized fields using store accessor. JSON, JSONB and HSTORE data types require AR 4.0 and up. Stores backed by a text field are supported in Rails 3.2.
Resolves #313, #186 and #150.
=> Add store accessor support for json, jsonb, and hstore datatypes

lib/activerecord-import/adapters/abstract_adapter.rb, lib/activerecord-import/adapters/mysql_adapter.rb, lib/activerecord-import/adapters/postgresql_adapter.rb, lib/activerecord-import/adapters/sqlite3_adapter.rb, lib/activerecord-import/import.rb, test/sqlite3/import_test.rb, test/support/mysql/import_examples.rb, test/support/postgresql/import_examples.rb, test/support/shared_examples/on_duplicate_key_ignore.rb
All three supported adapters (Postgres, MySQL, and SQLite) now support either `on_duplicate_key_ignore` or the alias `ignore` to  skip existing records on import.
Requires a primary key or unique index to identify duplicate records.
=> Add on_duplicate_key_ignore support for MySQL and SQLite

lib/activerecord-import/adapters/mysql_adapter.rb, lib/activerecord-import/adapters/sqlite3_adapter.rb, lib/activerecord-import/import.rb
Database adapters (SQLite, MySQL) that potentially break inserts into multiple queries should wrap statements in a transaction for atomicity. This would make it easier to recover from errors.
=> Wrap multiple database queries in transactions

README.markdown
The original wording implied that a constraint of `~> 0.3.0` should be used, but newest version works fine with rails 3.2.
=> Update version constraint for rails 3.2 in readme

lib/activerecord-import/adapters/postgresql_adapter.rb
When using multiple databases by extending ActiveRecord::Base, `ActiveRecord::Base.connection` refers wrong connection.
Therefore simply use `self.query_cache` instead of `ActiveRecord::Base.connection.query_cache`.
=> Avoid accessing ActiveRecord::Base.connection directly for multiple databases

lib/activerecord-import/import.rb, test/import_test.rb
Raises an error if the first element in the nested array is not an array
itself.
=> Raise ArgumentError on incorrect usage of nested arrays

lib/activerecord-import/adapters/sqlite3_adapter.rb, test/sqlite3/import_test.rb
Inserted IDs were being calculated based off last inserted ID, but that
is really just a hack that would cause more issues down the road than it
is worth. With uuids gaining popularity and the possibility of composite
primary keys, this just wasn't a good solution.
=> Revert recursive support for SQLite

.travis.yml, Gemfile
Work around to fix failing JRuby tests. Apparently Bundler 1.14.1 doesn't work with JRuby 9.0.5.0.
=> Update Travis build to use Bundler 1.13.7 for JRuby

lib/activerecord-import/adapters/postgresql_adapter.rb
Missing quotes cause an error where postgresql can't recognize the columns if their name is not entirely in lowercase letters.
=> Fixed missing quotes when returnings ids in postgresql

lib/activerecord-import/import.rb, test/import_test.rb, test/models/topic.rb, test/support/postgresql/import_examples.rb
Improves performance of importing with validations when models have uniqueness validators (See #228). Uniqueness cannot be guaranteed if there are duplicate values in the batch. Race conditions are also possible, so the only way to really preserve uniqueness is by using a database index.
With uniqueness validation removed, model validation could be done in combination with `:on_duplicate_key_update`, `:on_duplicate_key_ignore`, or `:ignore` for databases that support those options.
Just looking for feedback at this point, thanks!
=> Bypass uniqueness validation on import

lib/activerecord-import/import.rb, test/import_test.rb, test/models/topic.rb
Currently, `before_validation` callbacks are invoked, but `validate` ones are not. This fixes #409.
=> Respect "validate" callbacks

lib/activerecord-import/adapters/postgresql_adapter.rb, lib/activerecord-import/import.rb, test/support/shared_examples/on_duplicate_key_ignore.rb
When using :on_duplicate_key_ignore, Postgres only returns IDs for inserted records. This means that there is no way to know which models the returned IDs belong to so they cannot be set.
This resolves #411.
=> Prevent setting IDs when importing with on_duplicate_key_ignore

lib/activerecord-import/import.rb
Databases can allow expressions such as `CURRENT_TIMESTAMP` or functions for default values, so `read_attribute` must be used instead of `read_attribute_before_type_cast`.
=> Use read_attribute for columns with default value

lib/activerecord-import/import.rb, test/support/postgresql/import_examples.rb
This looks like it was a regression at some point.
Ids and timestamps must be assigned to models prior to marking the models as clean.
=> Mark clean after assigning attributes

lib/activerecord-import/value_sets_parser.rb, test/value_sets_bytes_parser_test.rb
It is possible that an insert with a single value set could exceed the max allowed byte size. For MySQL that would be the value for the `max_allowed_packet setting`. This raises a more helpful error when that is the case. See #437.
=> Raise error when value set byte size exceeds max allowed

lib/activerecord-import/import.rb
Hi,
In most cases a call to `primary_key` on an ActiveRecord::Base child class (model) will return a String instance which cannot be concatenated with an Array so we have to cast it into one prior to the `concat` call.
=> Fixed concat with 'primary_key'.

lib/activerecord-import/adapters/abstract_adapter.rb, lib/activerecord-import/adapters/mysql_adapter.rb, lib/activerecord-import/adapters/postgresql_adapter.rb, lib/activerecord-import/adapters/sqlite3_adapter.rb, lib/activerecord-import/import.rb, test/support/postgresql/import_examples.rb
The column or columns to return are specified using a `:returning` option, e.g.
```ruby
Book.import(books, returning: %w(author_name title))
```
The `ActiveRecord::Import::Result` struct is modified to include a `results` array attribute that contains the values for the returning columns.
If the table has a primary key, then the primary key fields are still requested and returned in the `ids` attribute.
=> Allow RETURNING to be specified for PostgreSQL

lib/activerecord-import/import.rb, test/import_test.rb, test/models/topic.rb, test/support/factories.rb, test/support/mysql/import_examples.rb
When `Validator` is iterating over a callback chain and skips unique validations, it shifts the index whenever it deletes such item from the collection. If there are several successive uniqueness validators, it omits the one following the deleted one in the chain. That prevents from inserting data in such model when running with `:validate` option.
Do not mutate the target chain inside the enumerator and iterate over a copy instead.
Relates to https://github.com/zdennis/activerecord-import/pull/301.
Follow-up for https://github.com/zdennis/activerecord-import/pull/410.
=> Fix bypassing uniqueness validators

lib/activerecord-import/import.rb, test/import_test.rb, test/models/topic.rb
When loading an array of hashes, the importer uses the same model instance whenever performs validations for each item. However, if there is a validator defined for a memoized attribute, it might provide false positives for valid values followed by invalid ones.
Instantiate a new object before validating a model to avoid such gotchas.
=> Reset model instance on validate

lib/activerecord-import/synchronize.rb
=> Use .unscoped to handle default scopes

lib/activerecord-import/import.rb, test/import_test.rb
Objects that respond to `.to_sql` (`ActiveRecord::Relation`) can be passed as values when importing
arrays or hashes. See #467.
=> Allow SQL subqueries to be passed as values

lib/activerecord-import/import.rb
Resolves #477. I'm not entirely sure why the inheritance column will return a mix of arrays and string values.
=> Fix issue importing STI models

lib/activerecord-import.rb, lib/activerecord-import/base.rb, lib/activerecord-import/import.rb
Fixes issue loading import support when activerecord-import is not autoloaded by Bundler and ActiveRecord has already established a connection to the database.
=> Load import support for currently active db adapter

lib/activerecord-import/import.rb, test/support/shared_examples/recursive_import.rb
This should resolve #488, but results in a subtle change when validating recursive imports. Only models with valid associations will be imported. Previously parent associations were imported regardless.
=> Fix validation logic for recursive import

lib/activerecord-import/adapters/abstract_adapter.rb, lib/activerecord-import/adapters/mysql_adapter.rb, lib/activerecord-import/adapters/postgresql_adapter.rb, lib/activerecord-import/import.rb, test/models/account.rb, test/models/bike_maker.rb, test/models/user.rb, test/schema/generic_schema.rb, test/support/shared_examples/on_duplicate_key_update.rb
Hi!
Thanks for making ActiveRecord-import!!
This is great gem!
I wanted to solve this problem
> It would be useful to automatically be able to increment the lock_version on duplicate key update.
#472 
* When checking if there is a lock_version column at the time of update processing, update it
Sorry for my poor English.
thank you for reading! (/･ω･)/
=>  Enabled to update lock_version of model

lib/activerecord-import/import.rb
In the latest version, `#import_without_validations_or_callbacks` raises "invalid slice size" exception because #each_slice is called with 0.
`#import_without_validations_or_callbacks` is a public API (Is my understanding correct?).
So it have to work even if `array_of_attributes` is empty.
=> Fix import_without_validations_or_callbacks fails if array is empty

lib/activerecord-import/import.rb, test/import_test.rb, test/models/user.rb, test/models/user_token.rb, test/schema/generic_schema.rb
When importing into an association, it was using the owner class table primary key (usually `id`) rather than the `:primary_key` option specified on the association.
=> Use the association primary key when importing

Rakefile, lib/activerecord-import/base.rb, test/adapters/makara_postgis.rb, test/makara_postgis/import_test.rb
As discussed in #526 there isn't support for the Makara Postgis adapter, so I figured I should change that.
This branch does fail the same tests as the existing postgis and postgresql adapters with the error `duplicate key value violates unique constraint "uk_code" DETAIL:  Key (code)=(abc) already exists.`
=> Add Makara Postgis adapter

lib/activerecord-import.rb
```
$ cat Gemfile
source "https://rubygems.org"
gem "activerecord-import"
```
```
$ bundle console
```
The console is started.
```
irb(main):001:0>
```
An error occurs.
```
There was an error while trying to load the gem 'activerecord-import'.
Gem Load Error is: uninitialized constant ActiveSupport
Backtrace for gem load error is:
/Users/onaka/.bundle/ruby/2.6.0/gems/activerecord-import-0.24.0/lib/activerecord-import.rb:3:in `<top (required)>'
/Users/onaka/.gem/ruby/2.6.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:81:in `require'
...
```
=> Add missing require for `ActiveSupport.on_load`

lib/activerecord-import/import.rb, test/support/postgresql/import_examples.rb
This fixes a regression introduced by #451 that prevents the `import` method from working with deeply frozen `on_duplicate_key_update` option hashes.
=> Handle deeply frozen on_duplicate_key_update options hashes

Gemfile, Rakefile, test/import_test.rb, test/support/factories.rb, test/support/generate.rb, test/support/shared_examples/recursive_import.rb, test/test_helper.rb
Factory Girl has been renamed to Factory Bot.
cf. https://github.com/thoughtbot/factory_bot/blob/master/NAME.md
And this PR suppresses the following Factory Bot's deprecation warning.
```
DEPRECATION WARNING: Static attributes will be removed in FactoryBot
5.0. Please use dynamic
attributes instead by wrapping the attribute value in a block:
title { "Tortilla Flat" }
To automatically update from static attributes to dynamic ones,
install rubocop-rspec and run:
rubocop \
--require rubocop-rspec \
--only FactoryBot/AttributeDefinedStatically \
--auto-correct
```
=> Use `Factory Bot` instead of `Factory Girl`

lib/activerecord-import/adapters/mysql_adapter.rb
Remove extraneous ';' from command to query mysql max_allowed_packet
There was an un-necessary semicolon at the end of the command to query
the MySQL servers max_allowed_packet global variable.
If ProxySQL was in between activerecord-import and the database then
this semicolon would cause "Mysql2::Error: Commands out of sync" errors.
These errors occur if multiple queries are performed without reading the
responses of all of them. The semicolon through ProxySQL caused an extra
query and these errors.
Remove the semicolon here as it is unnecessary, triggers a problem in
this particular case, and may cause issues in other cases also.
=> Allow .import to work with ProxySQL

README.markdown
Closes #442
Reorganize the README to explicitly have a section dedicated to usage of
activerecord-import, similar to how the wiki is currently laid out.
Add a note that the wiki is not to be added to going forward.
Migrate the callbacks wiki article to the README, plus add the example
from #442 to add an example of how callbacks and validations can
interact in a different fashion.
@zdennis @jkowens if you like this style I can also work on the others as I have time.
=> Start the README refactor and add a section for callbacks

lib/activerecord-import/import.rb, test/import_test.rb
Adds a "secret" option to include uniqueness validators. This is not a recommended approach because there are several pitfalls to attempting uniqueness validation, but in order to provide legacy support for projects that depend on this feature, this has been added back into the library.
=> Add option to include uniqueness validators

README.markdown
Closes https://github.com/zdennis/activerecord-import/issues/474
Replacement for https://github.com/zdennis/activerecord-import/wiki/Requiring
Part of https://github.com/zdennis/activerecord-import/issues/397
Follow up to https://github.com/zdennis/activerecord-import/pull/552
=> Add section about how to require activerecord-import

README.markdown
Closes https://github.com/zdennis/activerecord-import/issues/505
Closes https://github.com/zdennis/activerecord-import/issues/233
Another PR to hack away against https://github.com/zdennis/activerecord-import/issues/397. Follow up to https://github.com/zdennis/activerecord-import/pull/556 and https://github.com/zdennis/activerecord-import/pull/554.
=> Update README to add notes about conflicts with other gems

README.markdown
Followup to https://github.com/zdennis/activerecord-import/pull/560, https://github.com/zdennis/activerecord-import/pull/556, and, https://github.com/zdennis/activerecord-import/pull/554 in the series to address https://github.com/zdennis/activerecord-import/issues/397. 
Closes https://github.com/zdennis/activerecord-import/issues/430.
Closes https://github.com/zdennis/activerecord-import/issues/507. 
Migrates the following wiki articles into the README:
https://github.com/zdennis/activerecord-import/wiki
https://github.com/zdennis/activerecord-import/wiki/Counter-Cache-Column
https://github.com/zdennis/activerecord-import/wiki/Examples
https://github.com/zdennis/activerecord-import/wiki/How-to-run-the-tests
https://github.com/zdennis/activerecord-import/wiki/Note:-ActiveRecord-Timestamps …
=> Additional README updates

lib/activerecord-import/import.rb, test/import_test.rb, test/models/user_token.rb
Parent associations will not be checked to see if they exist, but instead the foreign key field will be checked for a value. Fixes #571.
=> Fix validating presence of belongs_to associations

lib/activerecord-import/import.rb, test/support/postgresql/import_examples.rb
There is a legal `ActiveRecord::Dirty.changes_applied` finalization method starting from `v4.1.8`.
It will clean the Dirty `changes` as usually, and will populate the `previous_changes` in additional - can be useful for further processing.
Actually, I need that right now :)
=> Move ActiveRecord::Dirty changes to previous_changes after import

lib/activerecord-import/import.rb, test/import_test.rb
Currently, when the user uses the arrays-of-arrays import mechanism, if there is more values than columns, it just produces broken SQL query such as
```
INSERT INTO table (col1, col2) VALUES ("val", "val2",)
```
Note the final comma. After it, there is a `nil` value that doesn't get printed. The reason the `nil` gets there is because if `column = columns[j]` in `values_sql_for_columns_and_attributes` overflows, `column` is going to be `nil` and not match any of the conditions, producing, again a `nil`.
A malformed SQL query is something definitely not desirable. I don't know about the general ideology behind this library, (whether you want to be loud about errors or ignore the case where there is too much data but you still manage to get on) but at least throwing an error message is …
=> A better error message for a corner case that resulted to hard-to-decipher errors.

lib/activerecord-import/import.rb
This PR fixes two instances of the "only setup alias if it isn't already defined" pattern.
The reason these two instances need a tweak is because they are within a `class << self` which involves the singleton (eigenclass) class and can be non-trivial to work with.
Inside of a `class << self` block, `self` actually refers to an instance, not a class, and it's actually unique - so these two `respond_to?` checks will actually never return true, because the unique `class << self` blocks don't define an `import` method.
Paste these examples into a rails console to see the output - the first one demonstrates the problem, the second one demonstrates the solution.
```
class ActiveRecord::Base
class << self
def bla
end
end
end
class ActiveRecord::Base
class << self
puts respond_to? :bla # returns …
```
=> Fix ActiveRecord::Base respond_to? check

lib/activerecord-import/import.rb, test/support/shared_examples/recursive_import.rb
Same reason `on_duplicate_key_update` is not passed to associations on
recursive import currently, must be applied to `returning` option, which
is otherwise unusable with recursive import.
=> Don't pass returning on recursive import

lib/activerecord-import/import.rb, test/schema/postgresql_schema.rb, test/support/postgresql/import_examples.rb
Well, `activerecord-import` silently corrupted a tons of the data on my server 💣
Fortunately, that was a staging one, and it's possible to revert this time 🍀 😃 
How that happened:
1) I have a pure `jsonb` postgres field - without default value (don't ask me why 😞), without `serialize` nor  `store_accessor` definition on model layer.
2) I use `ActiveRecord.import` with `on_duplicate_key_update` turned on.
3) everything is fine when the new value comes there for `jsonb` field. But...
4) if `jsonb` field was not changed - `activerecord-import` will take it from `AR#read_attribute_before_type_cast`. As a result in DB it will replace the original `jsonb` object with that object serialized to JSON **twice**. Postgres will silently accepts that, because such **string** is valid JSON string...
5) …
=> Fix import of saved json[b] fields for postgres

lib/activerecord-import/base.rb
Required for cockroachdb since it works with the postgresql adapter.
See https://www.cockroachlabs.com/docs/stable/build-a-ruby-app-with-cockroachdb-activerecord.html
=> add cockroachdb to adapter detection

README.markdown
Just got caught by this while testing AR-Import. the :validate option is overridden by the `import!` method. Here's an update to the Readme to make that a bit clearer.
=> Update README: :validate is overridden by `import!`

lib/activerecord-import/synchronize.rb
Fixes #622. Aggregations are now loaded lazily. See: https://github.com/rails/rails/commit/657060b5f8c14fc6249fc19231f703a7c749d84e#diff-391caa9b9464021e932ebf657fa9b13c
=> Clear aggregation cache if model uses aggregations

Gemfile
When install activerecord-import with Rails 5.1, it depends to sqlite3 `1.4`.
But Rails does not yet support the sqlite3 `1.4` system.
Therefore, installation of splite3 has failed.
https://travis-ci.org/zdennis/activerecord-import/jobs/552287397
The solution is to install the sqlite3 version `1.3.6`.
rails/rails#35153
I was worried that the build was an error and fixed it.
https://travis-ci.org/zdennis/activerecord-import
I tested in local environment as follows and confirmed that it works.
local environment
OS : macOS 10.14.6
Ruby : 2.5.1p57
Rails : 5.2.3
Thanks for making your project Open Source! Any feedback is greatly appreciated.
=> Fix sqlite3's version to 1.3.6 series

gemfiles/6.1.gemfile, lib/activerecord-import/base.rb
https://github.com/rails/rails/pull/37253 changed the connection pool
to pass in a database config instead of a specification - this updates
the base importer to be compatible with both
=> Update for Rails edge/6.1 alpha

README.markdown
The `:all_or_none` option was not documented and I made an edit to include it.
=> Update documentation to include description for :all_or_none option

lib/activerecord-import/import.rb
This PR fixes the issue mentioned in the #647 .
=> Use prepend pattern for ActiveRecord::Base#establish_connection patching

lib/activerecord-import/import.rb, test/schema/postgresql_schema.rb, test/support/postgresql/import_examples.rb
This PR fixes the issue described in https://github.com/zdennis/activerecord-import/issues/650.
By checking if the `.type` is `nil`, there is no longer a risk of calling `.to_sym` on a `nil` value.
I have added a `ENUM` field to the PostgreSQL schema for the tests. Because PostgreSQL does not support using `IF NOT EXISTS` on a `CREATE TYPE` statement, I had to implement the same logic by rescuing the correct exception type and then calling `ALTER TYPE` in the `rescue` block.
=> Fix NoMethodError when using PostgreSQL ENUM types

lib/activerecord-import/adapters/postgresql_adapter.rb, test/support/shared_examples/on_duplicate_key_update.rb
Fixes https://github.com/zdennis/activerecord-import/issues/655
For the record, the tricky case if `lock_version` is nullable and is null is handled neither by this gem, nor by AR (tested with v 4.2).
=> Fix #655: optimistic lock in Postgres

lib/activerecord-import/import.rb
After updating activerecord-import to v1.0.4, our project has started failing.
The cause of this problem is `#establish_connection` returns TrueClass/FalseClass (changed by #648).
Some gem expect the method to return `ActiveRecord::ConnectionAdapters::ConnectionPool` which is returned by original #establish_connection.
(I found this problem by using `activerecord-sharding` gem with activerecord-import.)
=> Fix compatibility issue because of not returning ActiveRecord::Connection from #establish_connection

lib/activerecord-import/import.rb
* Problem: If the column type is boolean with array: true, it fails with `can't quote Array` error
```
TypeError: can't quote Array
/vendor/bundle/2.6.5/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/quoting.rb:186:in `_quote'
/vendor/bundle/2.6.5/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/postgresql/quoting.rb:98:in `_quote'
/vendor/bundle/2.6.5/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/quoting.rb:23:in `quote'
/vendor/bundle/2.6.5/gems/activerecord-import-1.0.4/lib/activerecord-import/import.rb:953:in `block (2 levels) in values_sql_for_columns_and_attributes'
...
```
* Solution: Skip checking if it's boolean if it's a container of other types, such as ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Array, …
=> Support PostgreSQL array

lib/activerecord-import/import.rb, test/support/shared_examples/recursive_import.rb
We define association id even when we change this column, because of this it is impossible to set `nil`
Maybe we can skip such `load associations`, what do you think?
=> Skip load association ids when column changed

README.markdown
Adds a line in the introduction of the README that notes the `import` method might not be aliased as that, and would have to be called with `bulk_import` if other conflicting gems are present. Since the method is a such major and important part of this gem, I thought it would be best to quickly note this upfront since the debugging information encountered might be a bit mysterious.
=> Update README to note early on that `import` might be named `bulk_import` for compatibility reasons

.gitignore
The PR adds `benchmarks/log/` to `.gitignore`.
=> Add benchmarks/log/ to .gitignore

README.markdown, lib/activerecord-import/import.rb, test/import_test.rb
This change adds functionality that makes it easy to tell a user which of records in a dataset have failed validation. We found this to be particularly useful when dealing with imports from spreadsheets (e.g. `the record in line x has the following errors....`).
=> Provide a mechanism to map failures back to input

lib/activerecord-import/adapters/mysql_adapter.rb
In an effort to try to make a more cross DB compatible way to fetch the `max_allowed_packet` variable on AWS RDS MySQL instances migrated to via AWS DMS.
See: https://github.com/zdennis/activerecord-import/issues/705
=> use a more compatible mechanism for determining this session variable

activerecord-import.gemspec
This reduces unnecessary redirection from http://... to https://... when someone visits this gem's homepage via https://rubygems.org/gems/activerecord-import or some tools or APIs that use the gem's metadata.
=> GitHub is HTTPS by default

lib/activerecord-import/adapters/mysql_adapter.rb
@jkowens I sincerely apologize for this ... your sorta scooped up my PR faster than I was able to process it through our QA process for the application we are integrating this gem into... I think the result row has essentially only 1 column now given the new `SELECT @@` syntax... 
I would really like to backfill some spec/test code here, but I am having a really hard time finding the correct strategy for testing this code.
Site note: see also the rails implementation of `show_variable` https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/AbstractMysqlAdapter.html#method-i-show_variable (the @@ syntax is what they have been using since at least rails 4)
=> Fetch value from correct field/col from result row

lib/activerecord-import/import.rb
We run our application in `:strict` mass assignment error mode in our test suite, and make heavy use of the this gem ... I would like to propose switching back to the longer form of attribute assignment to prevent errors with some of our models.
If we could open a discussion on this PR it would be very helpful for us to understand why the change was made, and what options we have going forward.
It looks like the short-form of assignment was introduced here: https://github.com/zdennis/activerecord-import/compare/v1.0.5...v1.0.6#diff-70d0c2152cc72037bcf5c177f03eb9f8L700-L701
=> to prevent mass-assignment errors in strict mode

lib/activerecord-import/adapters/postgresql_adapter.rb
This PR is an attempt to fix an issue we experienced when migrating our rails app from 6.0 to 6.1.
We recently tried to migrate our Rails app to the latest version (6.1). Our test suites being green we decided to upgrade our production environment. That's when we started to see a random error:
`can't add a new key into hash during iteration` in `lib/active_record/connection_adapters/abstract/query_cache.rb`
This issue occurs in the `cache_sql` method: https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb#L115
Not all our rails app have this issue so it's definitively linked to a gem we are using. When searching in all our gems only one seems to manipulate the `@query_cache` object.
In your PG adapter, you use …
=> Better query cache clearing strategy

README.markdown, lib/activerecord-import/import.rb, test/import_test.rb
Hi there,
We have a pretty hairy problem whereby we are importing around 500k rows into a db from a spreadsheet uploaded by a user.
We have a progress bar on our app that displays the upload progress to the user, but the majority of the upload time is taken by the import (upwards of 95% of the total duration). To the user looking at the progress bar, it appears as if the upload has hung.
I've implemented a small feature into this super useful gem that allows us to send a proc as the value to a `batch_progress` option. If a callable is supplied, it will be fed these arguments:
* `rows_size` - the total amount of rows to be imported
* `num_batches` - the total amount of batches required
* `current_batch_number` - the current batch
* `batch_duration_in_secs` - how long this batch took in …
=> Support monitoring batched bulk importing progress by supplying a proc 

lib/activerecord-import/import.rb, test/support/shared_examples/recursive_import.rb
This handles the common use case of "I want to upsert an entire tree of models, replacing all the old content" without changing the options format.
=> Support :recursive in combination with on_duplicate_key_update: :all.

lib/activerecord-import/import.rb, test/import_test.rb, test/models/customer.rb, test/models/order.rb, test/schema/generic_schema.rb, test/support/postgresql/import_examples.rb
We use partitioning and for this, we need to include a partition key into each request. Hence, we need to redefine simple `belongs_to`, `has_many` to have (foreign_key, partition_key) as association connection. For example, if we partition tables by `account_id` and we have two tables `customers` and `orders`:
```ruby
#
#
class Customer < ActiveRecord::Base
has_many :orders,
inverse_of: :customer,
primary_key: %i[account_id id],
foreign_key: %i[account_id customer_id]
end
#
#
class Order < ActiveRecord::Base
belongs_to :customer,
inverse_of: :orders,
primary_key: %i[account_id id],
foreign_key: %i[account_id customer_id]
end
```
We will get account_id as part the generated SQL when associations are called:
```ruby
customer = Customer.where(account_id: 1).first
customer.orders
=> SELECT * …
```
=> Add support for compound foreign keys

lib/activerecord-import/adapters/postgresql_adapter.rb, lib/activerecord-import/adapters/sqlite3_adapter.rb
Hello,
`#database_version` is a public method in Rails. By overriding it, and making it private `activerecord-import` have side effects on some Rails features. Like structure dump since https://github.com/rails/rails/pull/43216.
```
NoMethodError: private method `database_version' called for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x00007f8d71dc7480>
```
In this PR I make `database_version` public again.
Have a good day ☀️
=> ActiveRecord `#database_version` is a public method

.github/workflows/test.yaml, lib/activerecord-import/adapters/mysql_adapter.rb, lib/activerecord-import/adapters/postgresql_adapter.rb, lib/activerecord-import/adapters/sqlite3_adapter.rb, test/support/postgresql/import_examples.rb
Enable compatibility for frozen string literals for newer rails versions.
This allows apps to be run with `RUBYOPT="--enable-frozen-string-literal"`
=> enable frozen string literals

README.markdown, benchmarks/benchmark.rb, test/import_test.rb, test/test_helper.rb
This PR is a follow-up to #752.
The following deprecation warning is displayed when I run CI with Rails 7.0.
```
DEPRECATION WARNING: ActiveRecord::Base.default_timezone= is deprecated and will be removed in Rails 7.1.
Use `ActiveRecord.default_timezone=` instead.
(called from <top (required)> at /home/runner/work/activerecord-import/activerecord-import/test/test_helper.rb:61)
```
This PR will suppress it.
=> Call `ActiveRecord.default_timezone=` if possible

.github/workflows/test.yaml, Gemfile
* Remove consideration of Ruby 1.9 and 2.3 which are not supported 
* Enable ruby/setup-ruby's `bundler-cache` to use caching
* Split test and lint, and run RuboCop only once
=> Refactor CI

.github/workflows/test.yaml, Gemfile, test/test_helper.rb
This PR adds the Ruby 3.0 and 3.1 to the CI matrix, and does the following:
* Split tests by DB to allow for skipping.
* Since [seamless_database_pool](https://github.com/bdurand/seamless_database_pool) requires Ruby ~> 2.0, skip installing it and running tests with it for Ruby 3.0+.
* Use `YAML.safe_load_file` to allow the use of aliases with Ruby 3.1.
* Remove `rb-readline` from Gemfile to suppress a bunch of warnings.
And I confirmed all CIs are green.
=> CI against Ruby 3.0 and 3.1

gemfiles/7.0.gemfile, lib/activerecord-import/import.rb, test/import_test.rb, test/models/tag.rb, test/models/tag_alias.rb, test/schema/generic_schema.rb
Without this change, such imports fail with an error such as `TypeError: [:tag_id, :parent_id] is not a symbol nor a string`.
<details>
<summary><h4>Backtrace</h4></summary>
<pre>…/gems/activemodel-7.0.4/lib/active_model/validator.rb:150:in `block in validate'
…/gems/activemodel-7.0.4/lib/active_model/validator.rb:149:in `each'
…/gems/activemodel-7.0.4/lib/active_model/validator.rb:149:in `validate'
…/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:423:in `block in make_lambda'
…/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
…/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:687:in `block (2 levels) in default_terminator'
…/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:686:in `catch' …
=> Fix importing models that are required to belong to models with composite primary keys

lib/activerecord-import/adapters/abstract_adapter.rb, lib/activerecord-import/adapters/mysql_adapter.rb, lib/activerecord-import/adapters/postgresql_adapter.rb, lib/activerecord-import/adapters/sqlite3_adapter.rb, lib/activerecord-import/import.rb, test/models/topic.rb, test/schema/generic_schema.rb, test/support/shared_examples/on_duplicate_key_update.rb
Probably it's related to issues:
https://github.com/zdennis/activerecord-import/issues/728:
```
class MyModel < ActiveRecord::Base
alias_attribute :foo, :baz
end
MyModel.import(%i[foo bar], %w[value_foo, value_baz], validate: false, on_duplicate_key_update: { conflict_target: %i[bar], columns: %i[foo] })
```
https://github.com/zdennis/activerecord-import/issues/795:
```
class MyModel < ActiveRecord::Base
self.ignored_columns = [:bar]
end
MyModel.import(%i[foo bar], %w[value_foo, value_baz], validate: false, on_duplicate_key_ignore: true)
MyModel.import(%i[foo bar], %w[value_foo, value_baz], validate: false, on_duplicate_key_update: { conflict_target: %i[foo], columns: %i[bar] })
```
=> Introduce support for alias attributes

lib/activerecord-import/adapters/mysql_adapter.rb
Hello !
Query splitting does not work well when column names contain multibyte characters.
Here is an example of a table schema that causes problems.
```
create_table :topics, force: :cascade do |t|
t.string 'あいう'  
end
```
=> Support for multi-byte column names when splitting queries

.github/workflows/test.yaml, Gemfile
This PR adds Ruby 3.2 to the test matrix.
Also, update `pry`  to the latest version to support Ruby 3.2.
Ref: https://github.com/pry/pry/blob/master/CHANGELOG.md#v0142v0142-january-9-2023
=> CI against Ruby 3.2

Gemfile, lib/activerecord-import/import.rb, test/test_helper.rb
Fixes https://github.com/zdennis/activerecord-import/issues/787
=> Send nil to ActiveSupport#compile which now requires a parameter

Dockerfile, README.markdown, docker-compose.yml, test/database.yml.sample
Make it easier for people to develop using Docker.
Add a Dockerfile and docker-compose.yml to help developers be able to pull an image and run the application locally. You can read the README for how to do this. I went for the most minimal change to get mysql working first.
The next step would be to add `postgresql` as a service so someone can run the tests against that database service.
=> Feature:  Add Dockerfile and compose file

Dockerfile, docker-compose.yml, test/database.yml.sample, test/support/shared_examples/recursive_import.rb
Add Postgresql to the Dockerfile and docker-compose.yml
Add necessary packages to the Dockerfile and add postgresql as a service. I also took the opportunity of fix a deprecation warning in the project around a minitest assertion
=> Feature:  add postgresql to Docker and docker compose file

.github/workflows/test.yaml
The `Checkout` action V2 uses old Node.js. It causes a lot of warnings and bump version to fix those.
Ref: "Annotations" section in https://github.com/zdennis/activerecord-import/actions/runs/6556382678
=> Bump `Checkout` action to V4

.github/workflows/test.yaml, gemfiles/7.1.gemfile, test/schema/generic_schema.rb
This PR adds Rails 7.1. to the CI matrix.
I didn't add `composite_primary_keys` gem to Gemfile because it doesn't support Rails 7.1 yet. Ref: [Is gem still relevant with Rails 7.1?](https://github.com/composite-primary-keys/composite_primary_keys/issues/608)
=> CI against Rails 7.1

lib/activerecord-import/import.rb, test/support/shared_examples/on_duplicate_key_update.rb
`activerecord-import` is ignoring the [`ActiveRecord::Base.lock_optimistically = false`](https://api.rubyonrails.org/classes/ActiveRecord/Locking/Optimistic.html) flag and it still updates the lock field.
Use the [`locking_enabled?`](https://api.rubyonrails.org/classes/ActiveRecord/Locking/Optimistic/ClassMethods.html#method-i-locking_enabled-3F) method provided by activerecord to decide whether the lock field should be updated.
=> Use ActiveRecord::Base.locking_enabled? to update the lock field

.github/workflows/test.yaml, Gemfile, Rakefile, lib/activerecord-import/active_record/adapters/trilogy_adapter.rb, lib/activerecord-import/adapters/trilogy_adapter.rb, test/adapters/trilogy.rb, test/database.yml.sample, test/github/database.yml, test/trilogy/import_test.rb
Bring support for the [Trilogy adapter](https://github.blog/2022-08-25-introducing-trilogy-a-new-database-adapter-for-ruby-on-rails/)to this project. I work on a Rails project and would like to switch to this new adapter. When running our CI I discovered this gem didn’t have support. Which then pointed to a child dependency that needed that support. I added that [here](https://github.com/composite-primary-keys/composite_primary_keys/pull/607).
=> [Feature]  Add trilogy adapter support

README.markdown
Closes #587 
Thank you for this wonderful library! I have always found this library useful.
I also had a hard time finding the index_predicate option for on_duplicate_key_update as described in this Issue.
So I added an example to the README.
=> Add index_predicate example to README

.github/workflows/test.yaml
With the new release of this gem we updated the version of jruby https://github.com/zdennis/activerecord-import/commit/0b22f67d5d0f69f86244de8caee658ba80b56430. 
We were currently matching on `jruby`, but let's make sure we never run against `jruby` if the  matrix ruby contains `jruby`.
=> Fix jruby spec runs

.github/workflows/test.yaml
This PR adds Ruby 3.3 to the CI matrix to ensure `activerecord-import` work with Ruby 3.3
=> CI against Ruby 3.3

README.markdown
Hey. I found the info in this issue https://github.com/zdennis/activerecord-import/issues/765 really helpful and since it has been a couple years thought it might need some help getting into the readme.
=> update readme for validates_uniqueness option

.gitignore, lib/activerecord-import/import.rb, test/models/author.rb, test/models/book.rb, test/models/composite_book.rb, test/models/composite_chapter.rb, test/models/customer.rb, test/models/order.rb, test/models/tag.rb, test/models/tag_alias.rb, test/schema/postgresql_schema.rb, test/support/postgresql/import_examples.rb, test/support/shared_examples/recursive_import.rb, test/test_helper.rb
Adding support for Rails 7.1 composite primary keys (issue #830 )
For Rails 7.1 I am making the assumption that the [composite-primary-keys](https://github.com/composite-primary-keys/composite_primary_keys) gem is not going to be used, since Rails 7.1 has out-of-the-box support for composite PKs. I have added some inline comments in the PR for the reviewers.
=> Rails 71 composite pks

activerecord-import.gemspec
Supported here: https://guides.rubygems.org/specification-reference/#metadata Useful for running https://github.com/MaximeD/gem_updater
=> Add changelog_uri to gemspec

benchmarks/lib/base.rb, benchmarks/lib/cli_parser.rb, lib/activerecord-import/import.rb
Fixes the warning with Ruby 3.3.5:
warning: .../ruby/3.3.5/lib/ruby/3.3.0/ostruct.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0. You can add ostruct to your Gemfile or gemspec to silence this warning.
OpenStruct use officially discouraged
https://docs.ruby-lang.org/en/master/NEWS/NEWS-3_0_0_md.html
https://docs.ruby-lang.org/en/master/OpenStruct.html#class-OpenStruct-label-Caveats
=> Remove OpenStruct

.github/workflows/test.yaml
The `ubuntu-latest` now uses the Ubuntu-24.04 image.
https://github.com/actions/runner-images/issues/10636
In the Ubuntu-24.04 image, `libsqlite3-dev`, which was installed in the Ubuntu 22.04 image, is no longer included.
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
Therefore, the installation of the `sqlite3` gem fails.
It is necessary to explicitly install the `libsqlite3-dev` package.
Since `jruby-9.4.5.0` and `jruby-9.3.10.0` for Ubuntu-24.04 do not exist, it is necessary to update them accordingly.
https://github.com/ruby/ruby-builder/releases
=> Fixing CI failures

Gemfile, test/test_helper.rb
This PR removes an outdated debugging requirement from our test helper and Gemfile. Because Our test matrix in [.github/workflows/test.yaml](https://github.com/zdennis/activerecord-import/blob/b38064538c144e58c9cf59e9b7e4ece556389823/.github/workflows/test.yaml) only includes Ruby versions 2.6 and above.
Additionally, JRuby will never meet the condition `RUBY_VERSION.to_f < 1.9`.
```
❯ mise exec ruby@jruby-9.4.8.0 -- ruby -e 'puts "#{JRUBY_VERSION}, #{RUBY_VERSION}"'
9.4.8.0, 3.1.4
❯ mise exec ruby@jruby-9.3.15.0 -- ruby -e 'puts "#{JRUBY_VERSION}, #{RUBY_VERSION}"'
9.3.15.0, 2.6.8
```
=> Remove outdated ruby-debug requirement

gemfiles/4.2.gemfile, gemfiles/5.0.gemfile, gemfiles/5.1.gemfile
Removes gemfiles for ActiveRecord versions 4.2, 5.0, and 5.1 as they are not referenced in the `AR_VERSION` matrix of [`.github/workflows/test.yaml`](https://github.com/zdennis/activerecord-import/blob/b38064538c144e58c9cf59e9b7e4ece556389823/.github/workflows/test.yaml) . These gemfiles are not being used in our CI workflow.
=> Remove legacy ActiveRecord version gemfiles (4.2, 5.0, 5.1)

.github/workflows/test.yaml, Gemfile, gemfiles/8.0.gemfile, test/models/author.rb, test/models/book.rb, test/models/composite_book.rb, test/models/composite_chapter.rb, test/models/customer.rb, test/models/order.rb, test/models/tag_alias.rb
This PR updates our CI configuration to test against Rails 8.0 and addresses two breaking changes:
1. Updates test code to handle the modified `enum` behavior introduced in https://github.com/rails/rails/commit/b9226a68bb18283f9f80e73c4bfa77f2a5309740
2. Replaces `query_constraints` with `foreign_key` to address the exception raising in https://github.com/rails/rails/commit/1a0b4d7dc0fa115e73e32bf0af22d3846b408eeb
=> CI against Rails 8.0

Gemfile, test/import_test.rb, test/models/book.rb, test/support/active_support/test_case_extensions.rb, test/support/mysql/import_examples.rb, test/support/postgresql/import_examples.rb, test/test_helper.rb
Removes legacy ActiveRecord version conditions from Gemfile and test files as they are not referenced in the `AR_VERSION` matrix of [`.github/workflows/test.yaml`](https://github.com/zdennis/activerecord-import/blob/9888643430adaf8a1a90d80b953abb0bc9a361a6/.github/workflows/test.yaml). These version-specific code paths are no longer being used in our CI workflow.
=> Remove legacy ActiveRecord version conditions from Gemfile and test files

lib/activerecord-import/mysql2.rb, lib/activerecord-import/postgresql.rb, lib/activerecord-import/sqlite3.rb
Since it's been a considerable amount of time since the warning was added in https://github.com/zdennis/activerecord-import/commit/163f5c64be3f357edfe15a1e393d447938437978, it should be safe to remove it now.
=> Remove deprecated ActiveRecord import adapter files

.github/workflows/test.yaml, CHANGELOG.md, Rakefile, lib/activerecord-import/base.rb, lib/activerecord-import/version.rb, test/adapters/mysql2_proxy.rb, test/adapters/postgresql_proxy.rb, test/database.yml.sample, test/github/database.yml, test/mysql2_proxy/import_test.rb, test/postgresql_proxy/import_test.rb
* Add Support for `active_record_proxy_adapters` gem. Since Rails 7.1 and above the support for 
makara is gone. It is no longet maintained. Developers are left struggling. folks over at @nasdaq have written a gem called
[active_record_proxy_adapters](https://rubygems.org/gems/active_record_proxy_adapters) which
does the same thing. Since this gem has its own adapter called `postgresql_proxy` we need to add the same as per the discussions [here.](https://github.com/Nasdaq/active_record_proxy_adapters/issues/20)
=> Add Support for ActiveRecord Proxy Adapters

lib/activerecord-import/import.rb
Replace redundant ternary operator with double pipes (||) operator
=> Fix Style/RedundantCondition lint error in import.rb

.github/workflows/test.yaml, Gemfile
This PR adds Ruby 3.4 support to the CI matrix. It includes conditional dependencies (`mutex_m`, `drb`, `base64`, `bigdecimal`) required for ActiveSupport 6.1-7.0 compatibility with Ruby 3.4, as these gems were moved from default to bundled gems.
=> CI against Ruby 3.4

lib/activerecord-import/adapters/mysql_adapter.rb, lib/activerecord-import/import.rb, test/support/shared_examples/affected_rows.rb
Problem: `affected_rows` always returned `0` for `ON DUPLICATE KEY UPDATE` operations in Trilogy adapter.
Root Cause: In this [PR](https://github.com/zdennis/activerecord-import/pull/882), we had used `raw_connection.affected_rows` which returns stale/incorrect values for ON DUPLICATE KEY UPDATE in Trilogy.
The correct values are available in `result.affected_rows` from the execute result object, so this simply changes the implementation to make use of the result rather than the connection to fetch the `affected_rows`, super simple change.
This PR:
Switch from `raw_connection.affected_rows` to `result.affected_rows` when available
Preserve `nil` for adapters without support
Adds a test to cover for that edge case
Fix batch accumulation to handle nil values properly
=> Fix affected_rows data source for ON DUPLICATE KEY UPDATE operations
