lib/activerecord-import/import.rb
test/import_test.rb
test/models/book.rb
test/schema/generic_schema.rb
test/schema/mysql_schema.rb

Sorry, I made a mess on my fork which made me reset and recreate the pull request.
I also added two tests for importing enum fields with both integer value and label (Rails > 4.1).

Fix Rails 4.2 Enum Support, fix for #139

---

README.markdown

Add image to display build status.

Add CI badge to README

---

lib/activerecord-import.rb

Don't directly touch AR::Base, but do it via AS.on_load

---

.travis.yml
gemfiles/5.0.gemfile
lib/activerecord-import/import.rb
lib/activerecord-import/synchronize.rb
test/import_test.rb
test/travis/build.sh

Work in progress for getting activerecord-import to work with ActiveRecord 5.0.0 / Rails 5.0.0
Related to issue #222 .

Work with Activerecord 5.0.0

---

lib/activerecord-import/import.rb
test/models/question.rb
test/models/rule.rb
test/schema/generic_schema.rb
test/support/factories.rb
test/support/postgresql/import_examples.rb

Fix issue importing has_one associations

---

Gemfile
test/test_helper.rb

JRuby doesn't support pry.
rbenv install jruby-9.0.4.0 &&
rbenv local jruby-9.0.4.0 &&
bundle &&
bundle exec rake test:jdbcmysql &&
bundle exec rake test:jdbcpostgresql

Fixing up things for running with jruby

---

benchmarks/benchmark.rb
benchmarks/lib/mysql2_benchmark.rb

These only run for Mysql right now, but they work:
ruby benchmarks/benchmark.rb

Fixing benchmarks to run

---

.travis.yml

This is working now, thanks to https://github.com/travis-ci/apt-package-whitelist/issues/368#issuecomment-198586476.

Use updated sqlite3 package on Travis CI

---

lib/activerecord-import/import.rb
test/import_test.rb

This simplifies logic for fetching and assigning attribute values for models. Includes code from #237.

Refactor attribute assignment for models

---

lib/activerecord-import/import.rb
test/import_test.rb
test/support/factories.rb

Fix association import method for polymorphic associations

---

CHANGELOG.md
lib/activerecord-import/version.rb

Prepping 0.14.0 release

---

lib/activerecord-import/adapters/postgresql_adapter.rb

I'm not sure if this is the best possible solution, but I figure this will help shed light on the problem.

Fix :no_returning option for JRuby

---

CHANGELOG.md
lib/activerecord-import/version.rb

0.14.1 release

---

lib/activerecord-import/import.rb
test/models/vendor.rb
test/schema/jdbcpostgresql_schema.rb
test/schema/postgis_schema.rb
test/schema/postgresql_schema.rb
test/support/postgresql/import_examples.rb

Resolves #311 and the issue that #138 has evolved into.

Support uuid primary keys

---

test/import_test.rb

Add test to confirm validate enabled by default

---

test/import_test.rb
test/schema/generic_schema.rb
test/support/factories.rb

Add test for importing models with no primary key

---

Gemfile
lib/activerecord-import/adapters/abstract_adapter.rb
lib/activerecord-import/import.rb
test/sqlite3/import_test.rb
test/support/shared_examples/recursive_import.rb
test/test_helper.rb

Warn if database does not support on_duplicate_key_update

---

lib/activerecord-import/import.rb
test/import_test.rb

prevent removing errors messages by duping original models error messages to failed instances

---

README.markdown

fix typo in readme

---

lib/activerecord-import/import.rb
test/support/postgresql/import_examples.rb

Allow uuid primary keys to be manually set

---

gemfiles/3.2.gemfile
gemfiles/4.0.gemfile
gemfiles/4.1.gemfile
gemfiles/4.2.gemfile
gemfiles/5.0.gemfile
lib/activerecord-import/adapters/postgresql_adapter.rb
lib/activerecord-import/import.rb
test/import_test.rb
test/models/book.rb
test/models/tag.rb
test/schema/generic_schema.rb
test/support/shared_examples/on_duplicate_key_ignore.rb
test/support/shared_examples/on_duplicate_key_update.rb
test/test_helper.rb

Add support for composite_primary_keys gem

---

lib/activerecord-import/import.rb
test/import_test.rb

Add support for importing array of hashes

---

lib/activerecord-import/import.rb

This is an attempt to resolve the Rails 5 performance hit noted in #357. Testing with the benchmark script to shows a nice improvement.

Improve Rails 5 import speed by memoizing type_caster

---

Gemfile
lib/activerecord-import/adapters/abstract_adapter.rb
lib/activerecord-import/adapters/mysql_adapter.rb
lib/activerecord-import/adapters/postgresql_adapter.rb
lib/activerecord-import/adapters/sqlite3_adapter.rb
lib/activerecord-import/import.rb
test/support/shared_examples/recursive_import.rb

Properly set returned ids when using composite primary keys

---

test/import_test.rb
test/models/car.rb
test/schema/generic_schema.rb
test/support/factories.rb

This will test errors being caused by unquoted column names.

Added test for column names with uppercase letters

---

lib/activerecord-import/import.rb
test/schema/postgresql_schema.rb
test/support/postgresql/import_examples.rb

Correctly deserialize columns with default values

---

lib/activerecord-import/import.rb

Allow for custom timestamp columns

---

lib/activerecord-import/import.rb
test/import_test.rb

Coerce boolean values when serializing for database

---

lib/activerecord-import/import.rb
test/import_test.rb
test/models/topic.rb

Run validation callbacks

---

lib/activerecord-import/import.rb

Update new_record? attribute when using :on_duplicate_key_ignore

---

lib/activerecord-import/adapters/postgresql_adapter.rb
lib/activerecord-import/import.rb
test/support/postgresql/import_examples.rb

**Description:**
Add an option to set WHERE condition in conflict_action, DO UPDATE SET command in PostgreSQL
[Doc](https://www.postgresql.org/docs/current/static/sql-insert.html) from PostgreSQL site.
Up #421

[#421] PostgreSQL, WHERE condition to in DO UPDATE SET command

---

lib/activerecord-import/import.rb
test/import_test.rb

Fix issue importing serialized attributes from saved models

---

lib/activerecord-import/import.rb

Load correct foreign key value when syncing associations

---

lib/activerecord-import/import.rb
test/import_test.rb

Fix issue importing models with polymorphic belongs_to associations

---

lib/activerecord-import/import.rb
test/import_test.rb

Adds an option to raise an error when passing an array of hashes to `import` and a hash contains keys which are not in `column_names`. Also clarifies in the docs that when passing only an array of hashes to `import` without explicit column names, the first hash's keys will be used as the columns to import.
The particular scenario that motivated this was using `activerecord-import` to migrate data from mongodb to postgres. It's not uncommon in mongo land for some document to not have a give key at all rather than setting the key to `null`. The result of passing mongo docs like this to `import` is that if you happen to have a doc first in the array that is missing some keys, but later docs in the same import do have those keys, they are silently ignored.  This can lead to spending several …

Add option to fail on unknown hash keys

---

lib/activerecord-import/import.rb

Other gems like elasticsearch-rails add an `.import` method to ActiveRecord::Base. This will resolve that name collision by allowing users to call `.bulk_import` instead. Hopefully `bulk_import` is more specific and less likely to clash with other libraries. Open to thoughts and discussion on this change.
Resolves #494 and #152.

Rename the import method to bulk_import and alias to import.

---

lib/activerecord-import/import.rb
test/support/shared_examples/recursive_import.rb

Problem at the association id updating. I have made fix, if it not the correct behavior

Fixed association ids

---

lib/activerecord-import/import.rb

Skip validating presence of belongs_to associations

---

lib/activerecord-import/import.rb

Validate models before building arrays of values

---

lib/activerecord-import/import.rb
test/support/postgresql/import_examples.rb
test/support/shared_examples/on_duplicate_key_update.rb

Add option to update all fields with on_duplicate_key_update

---

README.markdown

Closes https://github.com/zdennis/activerecord-import/issues/174
Another PR in the saga of
https://github.com/zdennis/activerecord-import/issues/397:
https://github.com/zdennis/activerecord-import/pull/563,
https://github.com/zdennis/activerecord-import/pull/560,
https://github.com/zdennis/activerecord-import/pull/556,
https://github.com/zdennis/activerecord-import/pull/554

Add README section for returns info of import

---

README.markdown

Closes https://github.com/zdennis/activerecord-import/issues/318
Closes https://github.com/zdennis/activerecord-import/issues/397

Add options table for import to README

---

lib/activerecord-import/adapters/mysql_adapter.rb

See issue https://github.com/zdennis/activerecord-import/issues/548.

Fix mysql duplicate key bug 

---

CHANGELOG.md
lib/activerecord-import/import.rb
lib/activerecord-import/version.rb
test/import_test.rb

Release v0.28.1

---

lib/activerecord-import/import.rb

Fix issue parsing timestamps with timezone info

---

lib/activerecord-import/adapters/postgresql_adapter.rb
test/support/shared_examples/recursive_import.rb

Ignore :no_returning when using :recursive

---

README.markdown

* fix wrong comment literal
* make Hash literal consistent (after 1.9 style is better for now, I guess)
* If you prefer before 1.9 style, I'll do so.

Tweak README

---

lib/activerecord-import/adapters/abstract_adapter.rb
lib/activerecord-import/adapters/postgresql_adapter.rb

Avoid NoMethodError when logger is nil

---

.travis.yml
Gemfile
gemfiles/6.0.gemfile
lib/activerecord-import/adapters/postgresql_adapter.rb
lib/activerecord-import/adapters/sqlite3_adapter.rb
test/support/sqlite3/import_examples.rb

Add support for ActiveRecord 6.0.0.rc1

---

lib/activerecord-import/import.rb

Fix issue validating STI models

---

lib/activerecord-import/import.rb
test/support/postgresql/import_examples.rb

Return an empty array for PostgreSQL results instead of nil

---

README.markdown

Remove offensive term

---

README.markdown

@jkowens - This PR adds the appropriate docs for import! 
Fixes #632

update docs for the import! method

---

README.markdown

Resolves https://github.com/zdennis/activerecord-import/issues/653

Document :validate_with_context option in README

---

lib/activerecord-import/import.rb
test/schema/postgresql_schema.rb
test/support/postgresql/import_examples.rb

Allow serialized attributes to be returned from import

---

README.markdown

This can be [confusing](https://github.com/zdennis/activerecord-import/issues/597), so this can help.

Document that hashes and arrays won't work in recursive mode.

---

LICENSE
README.markdown

Update license to MIT

---

lib/activerecord-import/import.rb
test/import_test.rb
test/models/animal.rb

-Handling after_initialize callback in validate: true by creating the model with hash immediately instead of looping
-Reused Animals table by creating a model with the desired callback
-Adding testcases for validate:true/false, handling after_initialize violation

handle after initialize on validate true - add test cases

---

lib/activerecord-import/adapters/abstract_adapter.rb
lib/activerecord-import/adapters/mysql_adapter.rb
lib/activerecord-import/adapters/postgresql_adapter.rb
lib/activerecord-import/adapters/sqlite3_adapter.rb
lib/activerecord-import/import.rb

Explicitly support on duplicate key update

---

CHANGELOG.md

It seems #698 doesn't exist, and #696 is correct.

Fix issue number in change log

---

CHANGELOG.md
README.markdown

I found tiny typos, so fixed them!

fix tiny typos

---

lib/activerecord-import/import.rb
test/import_test.rb
test/test_helper.rb

Fix importing STI models with ActiveRecord 6

---

lib/activerecord-import/active_record/adapters/jdbcmysql_adapter.rb

Include ActiveRecordImport in mysql2 connection adapter

---

.github/workflows/test.yaml
gemfiles/3.2.gemfile
gemfiles/4.0.gemfile
gemfiles/4.1.gemfile
gemfiles/7.0.gemfile
lib/activerecord-import/import.rb
lib/activerecord-import/synchronize.rb

Add support for ActiveRecord 7.0

---

README.markdown

* Fix a typo
* Use a correct language identifier to enable syntax highlighting
* Use the latest ActiveRecord version in a sample
* Update the link to CI results

docs: Minor fix

---

README.markdown

Updating the links to anchor links that fixes zdennis/activerecord-import#775

Fixes zdennis/activerecord-import#775

---

README.markdown

Highlight the NOTE in README.
See here.
https://github.com/community/community/discussions/16925

Highlight Notes in README

---

lib/activerecord-import/import.rb

I confront the same issue as #771 . So, fix it.

add index when models exists

---

lib/activerecord-import/import.rb

Stop memoizing schema column hash

---

README.markdown

- Change http to https
- Fix broken link

Update links in README
